# Generated by Django 4.2.1 on 2023-05-26 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('localizacao', models.CharField(max_length=100)),
                ('configuracoes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workstation')),
            ],
        ),
    ]
