# Generated by Django 4.2.1 on 2023-05-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workstation',
            old_name='numero',
            new_name='serial',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='status',
        ),
        migrations.AddField(
            model_name='reservas',
            name='checkin',
            field=models.BooleanField(default=False),
        ),
    ]
