# Generated by Django 4.2.1 on 2023-05-28 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_numero_workstation_serial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='comentarios',
        ),
    ]
